# Site settings
title: "suraj sharma"
description: no home of the mind > 
  Write a description of your website here.

author: Suraj Sharma
email: www.surajsharma@gmail.com
twitter_username: zeusraj
github_username: surajsharma


# If you are building a GitHub project page then use these settings:
url: "http://surajsharma.github.io/"
baseurl: ""

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title

sass:
    style: compressed

exclude: [vendor]
